/**************************************************************************************************
 * sven-teaser.js - Sven Teaser Plugin
 * @version: 2.1 (04-01-2016)
 * @url: svencreations.com
 *
 * @license Copyright (c) 2015, Sven Creations. All rights reserved.
 * This work is subject to the terms at http://codecanyon.net/licenses/standard
 *
 * @requires jQuery v1.7 or later (tested on 1.11.2)
 * @author Manoj Raj, rajmanoj.bottle@gmail.com
 *************************************************************************************************/
'use strict';(function(b){b.pluginOptions={autoStart:!0,controls:!0,fullDuration:"80",preloadMethod:"xhr",preloadFiles:[],loaderPreset:"bounceDelay",colors:["#E7464F","#CDAA20","#80993B","#07BABA","#9B2C9D"],showAnimationSummary:!1,onTeaserStart:function(){},onTeaserEnd:function(){},onBeforeScene:function(){},onAfterScene:function(){}};b.svenPlugin=function(d,P){function R(g,c,f){g=new b.BigVideo({useFlashForFirefox:!1,container:O,doLoop:g});g.init();g.show(c,{ambient:f});return g}function Za(b){console.log(b)}
function $a(g){aa&&("single-image"===A?(g=H.getResult("static-image"),S.addClass("sven-fullscreen").append('<img src="'+g.src+'" width="'+g.naturalWidth+'" height="'+g.naturalHeight+'" alt=""/>'),S=S.find("img")):(g=H.getResult("preview-image"),Q.addClass("sven-fullscreen").append('<img src="'+g.src+'" width="'+g.naturalWidth+'" height="'+g.naturalHeight+'" alt=""/>')));var c,f=0;Na.each(function(g,a){if(!I&&b(this).data().sceneVideo)0==f&&(b(this).data().sceneImage&&(c=H.getResult(b(this)[0].id),
Q.addClass("sven-fullscreen").append('<img src="'+c.src+'" width="'+c.naturalWidth+'" height="'+c.naturalHeight+'" alt=""/>')),f+=1);else if(b(this).data().sceneImage||b(this).data().mobileImage)c=H.getResult(b(this)[0].id),b(this).append('<div class="sven-fullscreen"><img src="'+c.src+'" width="'+c.naturalWidth+'" height="'+c.naturalHeight+'" alt=""/></div>')});p.find(".sven-fullscreen").fullscreenBackground({defaultCss:!1});ha&&(E=createjs.Sound.play(Oa),E.loop=ra,E.position=100,E.on("complete",
Ba),E.paused=!0,Ca.on("click",function(b){E.paused?(Da(),ba="playing"):(E.paused=!0,N.removeClass("fa-volume-up").addClass("fa-volume-off"),ba="paused")}));if(!Ea&&("video-bg"===A&&"youtube"===ca||!I&&0<da.length))T.on("YTPReady",function(){0===ma&&(ia=O.find(".mbYTP_wrapper"),sa(A))});else sa()}function sa(g){ea.hide();U.pause();b("body").addClass("set-overflow");"video-bg"===g&&(TweenMax.set(Q,{autoAlpha:0}),TweenMax.to(ia,.5,{autoAlpha:1}));F.init()}function Da(){if("undefined"!==typeof E){E.play();
var b=Math.round(E.duration),c=Math.round(1E3*t[n].totalTime().toFixed(1)),f=c%b;0<=ra?b*(ra+1)>c?(E.position=f,N.removeClass("fa-volume-off").addClass("fa-volume-up")):Ba():(E.position=f,N.removeClass("fa-volume-off").addClass("fa-volume-up"))}}function Ba(){E.paused=!0;N.removeClass("fa-volume-up").addClass("fa-volume-off")}function ta(){V&&h.pause();G&&G.YTPPause()}function ab(b){V&&h.currentTime(b);G&&G.YTPSeekTo(b)}function bb(g,c,f){c.data().sceneImage&&(c=H.getResult(c[0].id).src,Q.find("img").attr("src",
c).css({width:c.naturalWidth+"px",height:c.naturalHeight+"px"}),Q.fullscreenBackground({defaultCss:!1}));TweenMax.set(Q,{autoAlpha:1});if("html5"===f){fa=!0;ja=!1;TweenMax.set(na,{autoAlpha:1});var m=b.grep(W,function(a){return a.sceneIndex==g});-1==h.currentSrc().indexOf(m[0].videoURL)&&V.show(m[0].videoURL);h.off("timeupdate");h.off("ended");h.muted(m[0].mute);h.currentTime(m[0].startAt);if(Fa)1<W.length&&(Fa=!1),ua(),h.on("timeupdate",function(){if(0!=m[0].stopAt&&h.currentTime()>=m[0].stopAt||
0==m[0].stopAt&&h.currentTime()>=h.duration())m[0].loop?(h.loop(!0),h.currentTime(m[0].startAt),h.play()):(fa=!1,h.pause())}),h.play();else h.one("loadeddata",function(){ua();h.on("timeupdate",function(){if(0!=m[0].stopAt&&h.currentTime()>=m[0].stopAt||0==m[0].stopAt&&h.currentTime()>=h.duration())m[0].loop?(h.loop(!0),h.currentTime(m[0].startAt),h.play()):(fa=!1,h.pause())});h.play()})}else fa=!1,ja=!0,TweenMax.set(ia,{autoAlpha:1}),m=b.grep(da,function(a){return a.sceneIndex==g}),m[0].videoURL==
T[0].opt.videoURL?(ua(),G.YTPSeekTo(m[0].startAt),G.YTPPlay()):(m[0].autoPlay=!0,G.changeMovie(m[0]),T.one("YTPReady",function(){ua();b(this).YTPSeekTo(m[0].startAt);b(this).YTPPlay()}))}function ua(){TweenMax.set(Q,{autoAlpha:0})}function cb(){b.isFunction(y.onTeaserStart)&&y.onTeaserStart.call(d);db.one("click",function(b){t[n].currentLabel()!=Ga&&t[n].seek(Ga,!1).play()});"undefined"!==typeof E&&(!I&&eb&&"paused"!=ba||"playing"===ba?(Da(),E.paused=!1,N.removeClass("fa-volume-off").addClass("fa-volume-up"),
ba="playing"):(E.paused=!0,N.removeClass("fa-volume-up").addClass("fa-volume-off"),ba="paused"));"single-image"===A&&ga.paused()&&ga.resume();"video-bg"===A&&(Pa&&ab(va),V&&h.play(),G&&G.YTPPlay())}function fb(){Z.removeClass("fa-pause").removeClass("fa-play").addClass("fa-repeat");"undefined"!==typeof E&&gb&&Ba();"video-bg"===A&&Pa&&ta();b.isFunction(y.onTeaserEnd)&&y.onTeaserEnd.call(d)}function hb(){ea.wrapInner("<div class='stretcher loader'><div class='rect1'></div><div class='rect2'></div><div class='rect3'></div><div class='rect4'></div><div class='rect5'></div></div>");
ea.find(".stretcher > div").each(function(g,c){var f="+=0",m="+=0",a="+=0";0!=g&&(f="-=1.1",m="-=0.86",a="-=0.62");U.fromTo(b(this),.24,{scaleY:.4},{scaleY:1,ease:Linear.easeInOut},f);U.to(b(this),.24,{scaleY:.4,ease:Linear.easeInOut},m);U.to(b(this),.72,{scaleY:.4,ease:Linear.easeInOut},a)})}function ib(){ea.wrapInner("<div class='bouncer loader'><div class='bounce1'></div><div class='bounce2'></div><div class='bounce3'></div></div>");ea.find(".bouncer > div").each(function(g,c){var f="+=0",m="+=0";
0!=g&&(f="-=1.24",m="-=0.68");U.fromTo(b(this),.56,{scale:0},{scale:1,ease:Linear.easeInOut},f);U.to(b(this),.84,{scale:0,ease:Linear.easeInOut},m)})}function jb(b){ga=new TimelineMax({delay:0});var c=b.totalDuration();Qa=c+.75;Ha&&(ga.addLabel("imageZoomer"),b.add(ga,c));b.to(S,.75,{opacity:1})}function kb(){ga.pause()}function lb(b){"single-image"===A&&b.set(S,{autoAlpha:0,onComplete:kb,onCompleteParams:[]});"video-bg"===A&&b.set(O,{autoAlpha:0,onComplete:ta,onCompleteParams:[]})}function mb(g,
c,f,m){var a=f.trans,l=f.transDur,B,C=!1;B=0!=c?g.prevAll(".sven-slide:first"):b(".extinct");I||!f.sceneVideo&&!f.sceneImage&&"no"!==f.pursueVideo||(C=!0);m.set({},{onComplete:function(){b.isFunction(y.onBeforeScene)&&y.onBeforeScene.call(d,c,g)}});var X,e;X=g.find(".bt-container");if(0<X.length){var r=X.data().xStart?X.data().xStart:"-100%",z=X.data().fontMax?parseInt(X.data().fontMax):728;X.wrapInner("<div class='bt-wrapper'></div>");e=X.find(".bt-wrapper");e.bigtext({childSelector:"h1",maxfontsize:z});
m.set(X,{x:r})}"fade-in-bg"==a?(l="default"==l?1.4:parseFloat(l),l/=2,m.to(oa,l,{autoAlpha:1,ease:Linear.easeNone}),lb(m),m.set(B,{display:"none"}),C&&m.addLabel("hideP-"+c),m.set(g,{visibility:"visible"}),m.to(oa,l,{autoAlpha:0,ease:Linear.easeNone})):"off-on"==a?(l="default"==l?1.4:parseFloat(l),l/=2,m.to(oa,l,{autoAlpha:1,ease:Linear.easeNone}),m.set(B,{display:"none"}),C&&m.addLabel("hideP-"+c),m.set(g,{visibility:"visible"}),m.to(oa,l,{autoAlpha:0})):(m.set(B,{display:"none"}),C&&m.addLabel("hideP-"+
c),m.set(g,{visibility:"visible"}));C&&m.set({},{onStart:nb,onStartParams:[]},"hideP-"+c);!I&&f.sceneVideo&&m.set({},{onComplete:bb,onCompleteParams:[c,g,f.videoType]})}function nb(){G&&TweenMax.set(ia,{autoAlpha:0});na&&TweenMax.set(na,{autoAlpha:0});ta()}function Ra(b,c,f,m,a,l,B){a=J(b,f,m,a,!1,!1);var C,d,e,r,z,x,k;k=a.content0.data().staggerTime?parseFloat(a.content0.data().staggerTime):.08;r=a.content0.data().inEase?D(a.content0.data().inEase):"";z=a.content0.data().outEase?D(a.content0.data().outEase):
Circ.easeIn;x=a.split0;d=Ia(a.wrapper0);"halign-left"==a.slideAlignment||"halign-center"==a.slideAlignment?(C=d.offLeft,C="-"+Math.ceil(.6*C)+"px",d=Math.ceil(d.offRight+d.extWidth)+"px",e="sequential"):(C=d.offRight,C=Math.ceil(.6*C)+"px",d="-"+Math.ceil(d.offLeft+d.extWidth)+"px",e="reverse");l.set(a.wrapper0,{x:C});l.set(x.chars,{y:"-50%",opacity:0});e=a.content0.data().inPattern?a.content0.data().inPattern:e;x.chars=K(e,x.chars);B||(d="0px");if(a.content1){var h,q,u,v,Y,w,n,t;t=a.content1.data().staggerTime?
parseFloat(a.content1.data().staggerTime):.08;v=a.content1.data().inPattern?a.content1.data().inPattern:"sequential";Y=a.content1.data().inEase?D(a.content1.data().inEase):"";w=a.content1.data().outEase?D(a.content1.data().outEase):"";n=a.split1;h=Ia(a.wrapper1);q=Ia(a.backdrop1);"halign-left"==a.slideAlignment?(C=q.offLeft,e="right center",u="left center",B="-"+Math.ceil(C+q.extWidth)+"px",h=Math.ceil(h.offRight+h.extWidth)+"px",C=Ja(C,a.backdrop1),q=Math.ceil(q.offRight/q.extWidth)+2):(C=q.offRight,
e="left center",u="right center",B=Math.ceil(C+q.extWidth)+"px",h="-"+Math.ceil(h.offLeft+h.extWidth)+"px",C=Ja(C,a.backdrop1),q=Math.ceil(q.offLeft/q.extWidth)+2);l.set(a.backdrop1,{x:B,transformOrigin:e,scaleX:C});l.set(n.chars,{y:"-50%",opacity:0});n.chars=K(v,n.chars)}l.set(m,{visibility:"visible"});l.addLabel(a.marker);l=L(!1);l["in"].staggerTo(x.chars,.2,{y:"0%",opacity:1,ease:r},k,0);l["in"].to(a.wrapper0,l["in"].duration()+.1,{x:"0px"},0);a.content1&&(l["in"].to(a.backdrop1,1,{scaleX:1,x:0},
.18*l["in"].duration()),l["in"].staggerTo(n.chars,.2,{y:"0%",opacity:1,ease:Y},t,.8*l["in"].duration()));f.inDur&&l["in"].duration(parseFloat(f.inDur));"none"!=f.outDur&&(l.out.to(a.wrapper0,.5,{x:d,opacity:0,ease:z}),a.content1&&(l.out.to(a.backdrop1,.5,{scaleX:q,transformOrigin:u},"-=0.4"),l.out.to(a.wrapper1,.35,{x:h,opacity:0,ease:w},"-=0.3")),f.outDur&&l.out.duration(parseFloat(f.outDur)));M(b,l,c,f,a.marker,m,!1)}function ob(g,c,f,m,a,l){a=J(g,f,m,a,!1,!1);var B,C,d,e,r,z,x,k,h;h=a.content0.data().staggerTime?
parseFloat(a.content0.data().staggerTime):.08;e=a.split0;B=a.content0.data().inPattern?a.content0.data().inPattern:"random";C=a.content0.data().inEase?D(a.content0.data().inEase):"";d=a.content0.data().outEase?D(a.content0.data().outEase):"";e.chars=K(B,e.chars);b.each(e.chars,function(a,e){r=b(e).outerWidth();z=b(e).outerHeight();x=["rect(0px, 0px, 0px, 0px)","rect("+z+"px, "+r+"px, "+z+"px, "+r+"px)","rect("+z+"px, 0px, "+z+"px, 0px)","rect(0px, "+r+"px, 0px, "+r+"px)"];k=x[a%4];l.set(b(e),{clip:k})});
if(a.content1){var q,u;q=a.content1.data().inEase?D(a.content1.data().inEase):Bounce.easeOut;u=a.content1.data().outEase?D(a.content1.data().outEase):"";B=a.content1.hasClass("place-left")?"left top":a.content1.hasClass("place-right")?"right top":"center top";l.set(a.backdrop1,{scale:0,transformOrigin:B});l.set(a.content1,{opacity:0,transformOrigin:B})}l.set(m,{visibility:"visible"});l.addLabel(a.marker);var v=L(!0);b.each(e.chars,function(a,e){var g=(a+1)*h;r=b(e).outerWidth();z=b(e).outerHeight();
v.repeat.to(b(e),1.25,{clip:"rect(0px, "+r+"px, "+z+"px, 0px)",ease:C},g)});v["in"].add(v.repeat);a.content1&&(v["in"].to(a.backdrop1,.25,{scale:1.2,ease:Linear.easeNone}),v["in"].to(a.backdrop1,.6,{scale:1,ease:q}),v["in"].to(a.content1,.75,{opacity:1}));f.inDur&&v["in"].duration(parseFloat(f.inDur));"none"!=f.outDur&&(v.out.add(v.repeat.tweenFromTo(0,v.repeat.duration(),{ease:d}).timeScale(2).reverse()),a.content1&&v.out.to([a.content1,a.backdrop1],.6*v.out.duration(),{scale:0,ease:u},"-="+.8*v.out.duration()),
f.outDur&&v.out.duration(parseFloat(f.outDur)));M(g,v,c,f,a.marker,m,!0)}function pb(g,c,f,m,a,l){a=J(g,f,m,a,!1,!1);var B,d,h,e,r,z,x;x=a.content0.data().staggerTime?parseFloat(a.content0.data().staggerTime):.08;e=a.split0;B=a.content0.data().inPattern?a.content0.data().inPattern:"random";d=a.content0.data().inEase?a.content0.data().inEase:"";h=a.content0.data().outEase?D(a.content0.data().outEase):"";e.chars=K(B,e.chars);b.each(e.chars,function(a,e){r=b(e).outerWidth();l.set(b(e),{clip:"rect(0px, "+
r+"px, 0px, 0px)"})});if(a.content1){var k=a.content1.data().inEase?a.content1.data().inEase:Bounce.easeOut,n=a.content1.data().outEase?D(a.content1.data().outEase):"";l.set(a.wrapper1,{overflow:"hidden"});l.set([a.content1,a.backdrop1],{y:"-104%"})}l.set(m,{visibility:"visible"});l.addLabel(a.marker);var q=L(!0);b.each(e.chars,function(a,e){var g=a*x;r=b(e).outerWidth();z=b(e).outerHeight();q.repeat.to(b(e),1.5,{clip:"rect(0px, "+r+"px, "+z+"px, 0px)",ease:d},g)});q["in"].add(q.repeat);a.content1&&
q["in"].to([a.content1,a.backdrop1],.8,{y:"0%",ease:k});f.inDur&&q["in"].duration(parseFloat(f.inDur));"none"!=f.outDur&&(q.out.add(q.repeat.tweenFromTo(0,q.repeat.duration(),{ease:h}).timeScale(2).reverse()),a.content1&&q.out.to(a.wrapper1,.8,{opacity:0,ease:n},"-=1"),f.outDur&&q.out.duration(parseFloat(f.outDur)));M(g,q,c,f,a.marker,m,!0)}function qb(g,c,f,m,a,l){a=J(g,f,m,a,!1,!1);var B,d,h,e,r,z,x;x=a.content0.data().staggerTime?parseFloat(a.content0.data().staggerTime):.04;e=a.split0;B=a.content0.data().inPattern?
a.content0.data().inPattern:"random";d=a.content0.data().inEase?a.content0.data().inEase:"";h=a.content0.data().outEase?D(a.content0.data().outEase):"";e.chars=K(B,e.chars);b.each(e.chars,function(a,e){r=b(e).outerWidth();l.set(b(e),{clip:"rect(0px, "+r+"px, 0px, 0px)",scale:0})});if(a.content1){var k=a.content1.data().inEase?a.content1.data().inEase:Bounce.easeOut,n=a.content1.data().outEase?D(a.content1.data().outEase):"";l.set(a.wrapper1,{overflow:"hidden"});l.set([a.content1,a.backdrop1],{y:"-104%"})}l.set(m,
{visibility:"visible"});l.addLabel(a.marker);var q=L(!0);b.each(e.chars,function(a,e){var g=a*x;r=b(e).outerWidth();z=b(e).outerHeight();q.repeat.to(b(e),.8,{clip:"rect(0px, "+r+"px, "+z+"px, 0px)",scale:1,ease:d},g)});q["in"].add(q.repeat);a.content1&&q["in"].to([a.content1,a.backdrop1],.8,{y:"0%",ease:k});f.inDur&&q["in"].duration(parseFloat(f.inDur));"none"!=f.outDur&&(q.out.add(q.repeat.tweenFromTo(0,q.repeat.duration(),{ease:h}).timeScale(2).reverse()),a.content1&&q.out.to(a.wrapper1,.8,{opacity:0,
ease:n},"-=1"),f.outDur&&q.out.duration(parseFloat(f.outDur)));M(g,q,c,f,a.marker,m,!0)}function rb(g,c,f,m,a,l){a=J(g,f,m,a,!1,!1);var B,d,h,e;e=a.content0.data().staggerTime?parseFloat(a.content0.data().staggerTime):.15;h=a.split0;B=a.content0.data().inPattern?a.content0.data().inPattern:"sequential";a.content0.data().inEase&&a.content0.data();d=a.content0.data().outEase?D(a.content0.data().outEase):"";h.chars=K(B,h.chars);l.set(h.chars,{autoAlpha:0,scale:.7});if(a.content1){var r=a.content1.data().inEase?
a.content1.data().inEase:Bounce.easeOut,z=a.content1.data().outEase?D(a.content1.data().outEase):"";l.set(a.wrapper1,{overflow:"hidden"});l.set([a.content1,a.backdrop1],{y:"-104%"})}l.set(m,{visibility:"visible"});l.addLabel(a.marker);var x=L(!0);b.each(h.chars,function(a,g){x.repeat.addLabel("rotate-in-"+a,a*e);x.repeat.to(b(g),.35,{autoAlpha:1,rotation:30,transformOrigin:"center bottom",scale:1.1},"rotate-in-"+a);x.repeat.to(b(g),.25,{rotation:0,scale:1,transformOrigin:"center bottom",ease:Back.easeIn},
"rotate-in-"+a+"+=0.35")});x["in"].add(x.repeat);a.content1&&x["in"].to([a.content1,a.backdrop1],.8,{y:"0%",ease:r});f.inDur&&x["in"].duration(parseFloat(f.inDur));"none"!=f.outDur&&(x.out.add(x.repeat.tweenFromTo(0,x.repeat.duration(),{ease:d}).timeScale(2).reverse()),a.content1&&x.out.to(a.wrapper1,.8,{opacity:0,ease:z},"-=1"),f.outDur&&x.out.duration(parseFloat(f.outDur)));M(g,x,c,f,a.marker,m,!0)}function sb(g,c,f,m,a,l){a=J(g,f,m,a,!1,!1);var d=a.content0.data().inEase?a.content0.data().inEase:
SlowMo.ease.config(3,.7,!1),C=a.content0.data().outEase?D(a.content0.data().outEase):"",h=a.split0,e,r,z,x,k,n,q=1;a.content0.hasClass("place-left")?n="-"+Math.ceil(wa(a.wrapper0,g)+a.wrapper0.outerWidth())+"px":a.content0.hasClass("place-right")?n=Math.ceil(a.wrapper0.offset().left+a.wrapper0.outerWidth())+"px":(n=Math.ceil(a.wrapper0.offset().left+a.wrapper0.outerWidth())+"px",q=0);b(h.chars).each(function(a,g){r=Math.ceil(b(g).outerHeight()/4);e=Math.ceil(b(g).outerWidth()/2);for(var c=0;7>c;c++)b(g).parent().append(b(g).clone());
x=m.find(".sven-char-"+(a+1));for(c=0;2>c;c++)k="rect(0px, "+e*(c+1)+"px, "+1*r+"px, "+e*c+"px)",z=c,l.set(x.eq(z),{x:n,opacity:q,clip:k,force3D:!0});for(c=0;2>c;c++)k="rect("+1*r+"px, "+e*(c+1)+"px, "+2*r+"px, "+e*c+"px)",z=c+2,l.set(x.eq(z),{x:n,opacity:q,clip:k,force3D:!0});for(c=0;2>c;c++)k="rect("+2*r+"px, "+e*(c+1)+"px, "+3*r+"px, "+e*c+"px)",z=c+4,l.set(x.eq(z),{x:n,opacity:q,clip:k,force3D:!0});for(c=0;2>c;c++)k="rect("+3*r+"px, "+e*(c+1)+"px, "+4*r+"px, "+e*c+"px)",z=c+6,l.set(x.eq(z),{x:n,
opacity:q,clip:k,force3D:!0})});if(a.content1){var u=a.content1.data().inEase?a.content1.data().inEase:"",v=a.content1.data().outEase?D(a.content1.data().outEase):"",t;t=a.content1.hasClass("place-left")?"right center":a.content1.hasClass("place-right")?"left center":"center center";l.set(a.backdrop1,{scaleX:0,transformOrigin:t});l.set(a.content1,{opacity:0})}l.set(m,{visibility:"visible"});l.addLabel(a.marker);var w=L(!0);b(h.chars).each(function(a,b){x=m.find(".sven-char-"+(a+1));w.repeat.staggerTo(x,
.1,{x:0,opacity:1,ease:d},.08,1*Math.random())});w["in"].add(w.repeat,0);a.content1&&(w["in"].to(a.backdrop1,w.repeat.duration()-.2,{scaleX:1,ease:u},.2),w["in"].to(a.content1,.75,{opacity:1}));f.inDur&&w["in"].duration(parseFloat(f.inDur));"none"!=f.outDur&&(w.out.add(w.repeat.tweenFromTo(0,w.repeat.duration(),{ease:C}).timeScale(2).reverse()),u=w.out.duration(),a.content1&&(w.out.to(a.content1,.2*u,{opacity:0},0),w.out.to(a.backdrop1,.65*u,{scaleX:0,ease:v},0)),f.outDur&&w.out.duration(parseFloat(f.outDur)));
M(g,w,c,f,a.marker,m,!0)}function tb(g,c,f,m,a,l){a=J(g,f,m,a,!1,!1);var d,h,n,e,r;e=a.split0;r=a.content0.data().staggerTime?parseFloat(a.content0.data().staggerTime):.08;d=a.content0.data().inPattern?a.content0.data().inPattern:"random";h=a.content0.data().inEase?a.content0.data().inEase:"";n=a.content0.data().outEase?D(a.content0.data().outEase):"";e.chars=K(d,e.chars);if(a.content1){var z=a.content1.data().inEase?a.content1.data().inEase:Bounce.easeOut,x=a.content1.data().outEase?D(a.content1.data().outEase):
"";l.set(a.wrapper1,{overflow:"hidden"});l.set([a.content1,a.backdrop1],{y:"-104%"})}l.set(m,{visibility:"visible"});l.addLabel(a.marker);var k=L(!0);b.each(e.chars,function(a,e){var c=a*r;k.repeat.from(b(e),.8,{opacity:0,ease:h,force3D:!0},c)});k["in"].add(k.repeat);a.content1&&k["in"].to([a.content1,a.backdrop1],.8,{y:"0%",ease:z});f.inDur&&k["in"].duration(parseFloat(f.inDur));"none"!=f.outDur&&(a.content1&&k.out.to([a.content1,a.backdrop1],.1,{y:"-100%",ease:x}),k.out.add(k.repeat.tweenFromTo(0,
k.repeat.duration(),{ease:n}).timeScale(2).reverse()),f.outDur&&k.out.duration(parseFloat(f.outDur)));M(g,k,c,f,a.marker,m,!0)}function ub(g,c,f,m,a,l){a=J(g,f,m,a,!1,!1);var d,h,n,e,r,z=a.split0;e=a.content0.data().staggerTime?parseFloat(a.content0.data().staggerTime):.04;d=a.content0.data().inPattern?a.content0.data().inPattern:"random";h=a.content0.data().inEase?a.content0.data().inEase:Linear.easeNone;n=a.content0.data().outEase?D(a.content0.data().outEase):"";z.chars=K(d,z.chars);r=a.content0.css("color");
if(a.content1){var x,k,t,q;k=a.split1;t=a.content1.data().staggerTime?parseFloat(a.content1.data().staggerTime):.04;d=a.content1.data().inPattern?a.content1.data().inPattern:"random";x=a.content1.data().inEase?a.content1.data().inEase:Bounce.easeOut;a.content1.data().outEase&&D(a.content1.data().outEase);k.chars=K(d,k.chars);q=a.content1.css("color")}l.set(m,{visibility:"visible"});l.addLabel(a.marker);var u=L(!0);b.each(z.chars,function(a,c){var g=a*e;u.repeat.fromTo(b(c),.8,{opacity:0,textShadow:"0 0 20px "+
r,scale:1.2,color:"transparent",ease:h},{opacity:1,scale:1,color:r,textShadow:"0 0 0px "+r},g)});a.content1&&(u.repeat.addLabel("blurSub","+=0"),b.each(k.chars,function(a,e){var c="blurSub+="+a*t;u.repeat.fromTo(b(e),.8,{opacity:0,textShadow:"0 0 20px "+q,scale:1.2,color:"transparent",ease:x},{opacity:1,scale:1,textShadow:"0 0 0px "+q},c)}));u["in"].add(u.repeat);f.inDur&&u["in"].duration(parseFloat(f.inDur));"none"!=f.outDur&&(u.out.add(u.repeat.tweenFromTo(0,u.repeat.duration(),{ease:n}).timeScale(2).reverse()),
f.outDur&&u.out.duration(parseFloat(f.outDur)));M(g,u,c,f,a.marker,m,!0)}function vb(g,c,f,m,a,l){a=J(g,f,m,a,!1,!0);b.each(a.split0.lines,function(a,c){Math.ceil(b(c).outerHeight()/8);Math.ceil(b(c).outerWidth());for(var e=0;7>e;e++)b(this).after(b(c).clone());b(this).parent().find(".sven-line-"+(a+1)).each(function(a,e){l.set(b(e),{clip:"rect(0px, 0px, 0px 0px)"})})});a.content1&&l.set(a.wrapper1,{autoAlpha:0});l.set(m,{visibility:"visible"});l.addLabel(a.marker);var d=L(!0);b.each(a.split0.lines,
function(a,c){var e=Math.ceil(b(c).outerHeight()/8),g=Math.ceil(b(c).outerWidth()),f=b(this).parent().find(".sven-line-"+(a+1)),m=new TimelineMax;f.each(function(c,f){var d,l=0;d=0==c%2?"rect("+e*c+"px, 0px, "+e*(c+1)+"px, 0px)":"rect("+e*c+"px, "+g+"px, "+e*(c+1)+"px, "+g+"px)";4>c?(m.addLabel("pos-"+a+"-"+c),l="pos-"+a+"-"+c):l="pos-"+a+"-"+(7-c);m.fromTo(b(f),.6,{clip:d},{clip:"rect("+e*c+"px, "+g+"px, "+e*(c+1)+"px, 0px)"},l)});d.repeat.add(m,0)});d["in"].add(d.repeat);a.content1&&d["in"].to(a.wrapper1,
.75,{autoAlpha:1});f.inDur&&d["in"].duration(parseFloat(f.inDur));"none"!=f.outDur&&(d.out.add(d.repeat.tweenFromTo(0,d.repeat.duration()).timeScale(2).reverse()),a.content1&&d.out.to([a.wrapper1],.75,{autoAlpha:0},0),f.outDur&&d.out.duration(parseFloat(f.outDur)));M(g,d,c,f,a.marker,m,!0)}function wb(g,c,f,m,a,d){a=J(g,f,m,a,!1,!1);var h,n,t,e,r;e=a.split0;r=a.content0.data().staggerTime?parseFloat(a.content0.data().staggerTime):.08;h=a.content0.data().inPattern?a.content0.data().inPattern:"sequential";
n=a.content0.data().inEase?a.content0.data().inEase:Bounce.easeOut;t=a.content0.data().outEase?D(a.content0.data().outEase):"";e.chars=K(h,e.chars);var z=[],x,k,p;d.set(e.chars,{overflow:"hidden"});b.each(e.chars,function(a,c){x="sven-char-sub-"+(a+1);k=b(c).outerWidth();p=b(c).outerHeight();b(c).wrapInner("<div class='"+x+"' style='width: "+k+"px; height: "+p+"px'></div>");z.push(b(c).find("."+x))});d.set(z,{x:"-100%"});if(a.content1){var q,u,v,Y;u=a.split1;v=a.content1.data().staggerTime?parseFloat(a.content1.data().staggerTime):
.08;h=a.content1.data().inPattern?a.content1.data().inPattern:"sequential";q=a.content1.data().inEase?a.content1.data().inEase:"";a.content1.data().outEase&&D(a.content1.data().outEase);u.chars=K(h,u.chars);Y=a.content1.css("color")}d.set(m,{visibility:"visible"});d.addLabel(a.marker);var w=L(!0);b.each(z,function(a,c){var e=a*r;w.repeat.to(b(c),1.25,{x:"0%",ease:n},e)});a.content1&&(w.repeat.addLabel("blurSub","+=0"),b.each(u.chars,function(a,c){var e="blurSub+="+a*v;w.repeat.fromTo(b(c),.8,{opacity:0,
textShadow:"0 0 20px "+Y,scale:1.2,color:"transparent",ease:q},{opacity:1,scale:1,color:Y,textShadow:"0 0 0px "+Y},e)}));w["in"].add(w.repeat);f.inDur&&w["in"].duration(parseFloat(f.inDur));"none"!=f.outDur&&(w.out.add(w.repeat.tweenFromTo(0,w.repeat.duration(),{ease:t}).timeScale(2).reverse()),f.outDur&&w.out.duration(parseFloat(f.outDur)));M(g,w,c,f,a.marker,m,!0)}function xb(g,c,f,d,a,l){a=J(g,f,d,a,!0,!0);if(100>a.content0.outerHeight())var h=Math.ceil(a.content0.outerHeight()-1),n=1;else h=99,
n=Math.ceil(a.content0.outerHeight()/100);for(var t=a.content0.outerWidth(),e=0;e<h;e++)a.wrapper0.append(a.content0.clone());h=a.wrapper0.find("h1");h.each(function(a,c){l.set(b(c),{position:"absolute",left:0,top:0,x:0,opacity:1,clip:"rect("+n*a+"px, "+t+"px, "+n*(a+1)+"px, 0px)"})});l.set(a.wrapper0,{autoAlpha:0});a.content1&&l.set(a.wrapper1,{autoAlpha:0});l.set(d,{visibility:"visible"});l.addLabel(a.marker);var r=L(!0);r["in"].to(a.wrapper0,.75,{autoAlpha:1},0);h.each(function(a,c){r.repeat.to(b(this),
.1,{x:randomInt(-5,5),opacity:randomFloat(.8,1),ease:RoughEase.ease.config({strength:5,points:50,template:SlowMo.ease,clamp:!1,taper:"out"})},0)});r["in"].add(r.repeat,"+=0.2");pa(r["in"],r.repeat,h,1,!1,"+=0.1");pa(r["in"],r.repeat,h,.5,!1,"+=0.4");pa(r["in"],r.repeat,h,.5,!0,"+=3");pa(r["in"],r.repeat,h,.5,!1,"+=0.4");pa(r["in"],r.repeat,h,.5,!1,"+=2");r["in"].to(h,.25,{x:0,opacity:1,ease:RoughEase.ease.config({strength:5,points:50,template:SlowMo.ease,clamp:!1,taper:"out"})});r["in"].set(h,{x:0,
opacity:1});a.content1&&r["in"].to(a.wrapper1,.75,{autoAlpha:1},"comingSubContent");f.inDur&&r["in"].duration(parseFloat(f.inDur));"none"!=f.outDur&&(r.out.to([a.content0],.75,{autoAlpha:0},0),a.content1&&r.out.to([a.wrapper1],.75,{autoAlpha:0},0),f.outDur&&r.out.duration(parseFloat(f.outDur)));M(g,r,c,f,a.marker,d,!1)}function pa(b,c,f,d,a,l){b.to(f,.25,{x:0,opacity:1,ease:RoughEase.ease.config({strength:5,points:50,template:SlowMo.ease,clamp:!1,taper:"out"})});a&&b.addLabel("comingSubContent","+=0.3");
b.add(c.tweenFromTo(0,c.duration()).timeScale(d),l)}function J(g,c,f,d,a,l){var h={};h.marker=g.attr("id");g=g.children();var n;g.hasClass("halign-left")?(n="place-left",h.slideAlignment="halign-left"):g.hasClass("halign-right")?(n="place-right",h.slideAlignment="halign-right"):(n="place-center",h.slideAlignment="halign-center");g=Sa(f);var t=0;d.each(function(c,g){b(this).append("<div class='ws-fix'>&nbsp;</div>");var d=b(this).find(".ws-fix"),m=Math.ceil(d.outerWidth()+1);d.remove();h["content"+
c]=b(this);var k=Sa(b(this)),p=b(this).data().align?"place-"+b(this).data().align:n,d=b(this).data().boxType?b(this).data().boxType:"contain";b(this).wrap("<div class='content-wrapper-"+c+"' style='position:relative;width:100%;'></div>");h["wrapper"+c]=f.find(".content-wrapper-"+c);0!=c&&"contain"===d&&b(this).css("display","inline-block");b(this).css({display:"block",position:"absolute",width:Math.ceil(b(this).outerWidth()+m)+"px",height:Math.ceil(b(this).outerHeight())+"px"}).addClass("place-left");
if(0==c&&a||1==c&&l||1<c){var q;b(this).removeClass("place-left").addClass(p);h["wrapper"+c].css({height:Math.ceil(b(this).outerHeight())+"px"});q=Math.ceil(b(this).outerWidth());q>t&&(t=q)}else{h["split"+c]=new SplitText(b(this),{type:"words,chars,lines",wordsClass:"sven-word-++",charsClass:"sven-char-++",linesClass:"sven-line-++",position:"absolute"});b(this).removeClass("place-left").addClass(p);q=0;var u,v,Y=h["split"+c].lines.length;b.each(h["split"+c].lines,function(a,c){var g=b(c).children().last();
u=parseInt(g.css("left"))+parseInt(g.css("width"));b(c).css({width:u+"px",right:k.padRight+"px"}).addClass(p);u>q&&(q=u);a==Y-1&&(v=parseInt(b(this).css("top"))+parseInt(b(this).css("height")))});b(this).css({width:q+k.horz+"px",height:v+k.vert+"px"});h["wrapper"+c].css({height:v+k.vert+"px"});q>t&&(t=q+k.horz)}0<c&&(b(this).after("<div class='lt-boxed content-backdrop-"+c+"'></div>"),h["backdrop"+c]=f.find(".content-backdrop-"+c),m="full"==d?"100%":b(g).outerWidth()+"px",h["backdrop"+c].css({position:"absolute",
width:m,height:b(g).outerHeight()+"px"}),h["backdrop"+c].addClass(p))});f.css({width:t+g.horz+"px"});return h}function Ja(b,c){return c.outerWidth()>b?3:Math.ceil(b/c.outerWidth())+2}function Ia(b){var c={};c.offLeft=b.offset().left-p.offset().left;c.offRight=p.width()-(c.offLeft+b.outerWidth());c.extWidth=b.outerWidth();c.extHeight=b.outerHeight();return c}function Sa(b){var c={};c.padTop=parseInt(b.css("padding-top"));c.padRight=parseInt(b.css("padding-right"));c.padBottom=parseInt(b.css("padding-bottom"));
c.padLeft=parseInt(b.css("padding-left"));c.borTop=parseInt(b.css("border-top-width"));c.borRight=parseInt(b.css("border-right-width"));c.borBottom=parseInt(b.css("border-bottom-width"));c.borLeft=parseInt(b.css("border-left-width"));c.horz=c.padLeft+c.padRight+c.borLeft+c.borRight;c.vert=c.padTop+c.padBottom+c.borTop+c.borBottom;return c}function wa(b,c){return c.width()-(b.offset().left+b.outerWidth())}function L(b){var c={};c.in=new TimelineMax;c.out=new TimelineMax;c.full=new TimelineMax;b&&(c.repeat=
new TimelineMax);return c}function K(b,c){return"random"===b?shuffleArray(c):"reverse"===b?c.reverse():"median"===b?centerArray(c):"reverse-median"===b?centerArray(c).reverse():c}function D(b){var c=b.split(".");if(2===c.length)return window[c[0]][c[1]];b=b.match(/true|false|(-?\d*\.?\d*(?:e[\-+]?\d+)?)[0-9]/ig).map(JSON.parse);return window[c[0]][c[1]].config.apply(null,b)}function M(g,c,f,m,a,h,p){var C="default"==m.freezeTime?1.5:parseFloat(m.freezeTime);c.full.add(c["in"]);"none"!=m.outDur?(c.full.add(c.out,
"+="+C),c.full.set(h,{visibility:"hidden"})):c.full.set({},{},"+="+C);d.hasClass("animate-colors")&&(h=f%y.colors.length,c.full.to(d,c.full.duration(),{backgroundColor:y.colors[h]},0));p&&c.full.set({},{onComplete:function(){c.repeat.resume()}});m.sceneDur&&c.full.duration(parseFloat(m.sceneDur));y.showAnimationSummary&&(p="in: "+c["in"].duration().toFixed(1)+"s<br/> out: "+c.out.duration().toFixed(1)+"s<br/> freeze: "+C+"s<br/> scene: "+c.full.duration().toFixed(1)+"s",c.full.set(yb,{text:p},.1),
c.full.set(zb,{text:m.anim},.1));m=g.find(".bt-container");if(0<m.length){p=m.data().animate?m.data().animate:"yes";C=m.data().xEnd?m.data().xEnd:"0%";h=m.data().dur?parseFloat(m.data().dur):c["in"].duration();var A=m.data().ease?D(m.data().ease):Power4.easeOut;"yes"===p?t[n].to(m,h,{x:C,ease:A},a):t[n].set(m,{x:"0%"},a)}t[n].add(c.full,a);t[n].set({},{onComplete:function(){b.isFunction(y.onAfterScene)&&y.onAfterScene.call(d,f,g)}})}var F=this,y=b.extend({},b.pluginOptions,P),H,ka=[],W=[],da=[],A,
t={},n=d.attr("id"),Ta,I=isMobile.any,Ua=b(window).width(),Ga,ma=0,ha=d.attr("data-enable-sound")?parseBool(d.attr("data-enable-sound")):!1,Ab=d.attr("data-sound-loop")?parseBool(d.attr("data-sound-loop")):!1,eb=d.attr("data-auto-play-sound")?parseBool(d.attr("data-auto-play-sound")):!0,gb=d.attr("data-auto-stop-sound")?parseBool(d.attr("data-auto-stop-sound")):!1,ba,ra,Qa,ga,aa=d.attr("data-static-image")?parseBool(d.attr("data-static-image")):!1,Ka=d.attr("data-mobile-image")?parseBool(d.attr("data-mobile-image")):
!1,xa=d.data().zoomOrigin?d.data().zoomOrigin:"center center",Va=d.data().zoomType?d.data().zoomType:"in",La=d.data().zoomDur?parseFloat(d.data().zoomDur):"auto",Ha=d.data().zoomScale?parseFloat(d.data().zoomScale):!1,Fa=!1,qa=!1,fa=!1,ja=!1,Ea=!1,ca=d.data().videoType?d.data().videoType:"html5",ya=d.attr("data-mute-video")?parseBool(d.attr("data-mute-video")):!0;d.data().videoQuality&&d.data();var va=d.data().videoStart?parseInt(d.data().videoStart):0,za=d.data().videoStop?parseInt(d.data().videoStop):
0,Ma=d.attr("data-video-loop")?parseBool(d.attr("data-video-loop")):!0,Pa=d.attr("data-auto-stop-video")?parseBool(d.attr("data-auto-stop-video")):!1;A=d.data().staticVideo&&!I?"video-bg":aa||Ka?"single-image":"mixed";ra=Ab?-1:0;d.hasClass("animate-colors")&&b(d).css({"background-color":y.colors[0]});I&&Ka&&(aa=Ka);d.wrap("<div class='sven-wrapper'></div>");var p=d.parent();p.append("<div class='loader-container'></div>");var ea=p.find(".loader-container"),U=new TimelineMax({delay:0,repeat:-1,paused:!0});
"bounceDelay"===y.loaderPreset?ib():hb();U.play();if("single-image"===A){p.append("<div class='image-bg'></div><div class='black-bg'></div>");var S=p.find(".image-bg"),oa=p.find(".black-bg");ka.push({id:"static-image",src:aa})}else"video-bg"===A&&aa&&ka.push({id:"preview-image",src:aa}),p.append("<div class='black-bg'></div>"),oa=p.find(".black-bg");p.append("<div class='video-wrapper'><div class='video-overlay'></div><div class='preview-image'></div></div>");var Q=p.find(".preview-image");p.find(".video-overlay");
var O=p.find(".video-wrapper");0<y.preloadFiles.length&&b.each(y.preloadFiles,function(b,c){ka.push({src:c})});var Na=d.find(".sven-slide");Na.each(function(d,c){var f;if(b(this).data().sceneImage||b(this).data().mobileImage)b(this).data().sceneImage&&(f=b(this).data().sceneImage),I&&b(this).data().mobileImage&&(f=b(this).data().mobileImage),f&&ka.push({id:b(this)[0].id,src:f});if(!I)if("html5"==b(this).data().videoType){f=b(this).attr("data-mute-video")?parseBool(b(this).attr("data-mute-video")):
!0;var h=b(this).data().videoStart?parseInt(b(this).data().videoStart):0,a=b(this).data().videoStop?parseInt(b(this).data().videoStop):0,l=b(this).attr("data-video-loop")?parseBool(b(this).attr("data-video-loop")):!0;f={videoURL:b(this).data().sceneVideo,mute:f,startAt:h,stopAt:a,loop:l,sceneIndex:d};W.push(f)}else if("youtube"==b(this).data().videoType){f=b(this).attr("data-mute-video")?parseBool(b(this).attr("data-mute-video")):!0;var n=b(this).data().videoQuality?b(this).data().videoQuality:"highres",
h=b(this).data().videoStart?parseInt(b(this).data().videoStart):0,a=b(this).data().videoStop?parseInt(b(this).data().videoStop):0,l=b(this).attr("data-video-loop")?parseBool(b(this).attr("data-video-loop")):!1;f={autoPlay:!1,showYTLogo:!1,stopMovieOnBlur:!1,showControls:!1,opacity:1,videoURL:b(this).data().sceneVideo,containment:"."+O[0].className,quality:n,mute:f,startAt:h,stopAt:a,loop:l,sceneIndex:d};da.push(f)}});if(!I&&(0<W.length||0<da.length||"video-bg"===A)){ha&&(ya=!0);if("video-bg"===A&&
"html5"===ca||0<W.length){var V,h,na;"video-bg"===A&&"html5"===ca?(TweenMax.set(Q,{autoAlpha:1}),V=R(Ma,d.data().staticVideo,ya),h=V.getPlayer(),h.off("ended"),h.currentTime(va),h.on("loadeddata",function(){TweenMax.set(Q,{autoAlpha:0});TweenMax.to(na,.5,{autoAlpha:1});h.on("timeupdate",function(){if(0!=za&&h.currentTime()>=za||0==za&&h.currentTime()>=h.duration())Ma?(h.loop(!0),h.currentTime(va),h.play()):(qa=!0,h.pause())})})):(V=R(W[0].loop,W[0].videoURL,W[0].mute),h=V.getPlayer(),h.off("ended"),
h.currentTime(W[0].startAt),h.one("loadeddata",function(){Fa=!0}));na=O.find("#big-video-wrap")}if("video-bg"===A&&"youtube"===ca||0<da.length){"video-bg"===A&&"youtube"===ca?(TweenMax.set(Q,{autoAlpha:1}),O.append('<div id="bgndVideo" class="player" data-property="{showYTLogo: false, loop: '+Ma+", stopMovieOnBlur: false, showControls: false, videoURL: '"+d.data().staticVideo+"', containment:'."+O[0].className+"', autoPlay: false, mute: "+ya+", startAt: "+va+", stopAt: "+za+', opacity: 1}">My video</div>')):
O.append('<div id="bgndVideo" class="player" data-property='+JSON.stringify(da[0])+">My video</div>");var G=O.find("#bgndVideo"),ia,T=G.YTPlayer();T.on("YTPReady",function(){ia=O.find(".mbYTP_wrapper");Ea=!0});T.on("YTPEnd",function(){"video-bg"===A?qa=!0:ja=!1})}}if(y.showAnimationSummary){p.append("<div id='summary-handle'><i class='fa fa-info'></i></div><div id='summary-container'><div class='details'><h3 class='animation-name'></h3><p class='scene-info'></p><h3 class='total-duration'></h3></div></div>");
var Wa=p.find("#summary-handle"),zb=p.find("#summary-container .animation-name"),yb=p.find("#summary-container .scene-info"),Bb=p.find("#summary-container .total-duration")}p.append("<div class='controls-nav'></div>");var la=p.find(".controls-nav");if(y.controls){la.append("<a class='speed-label' title='Speed Up/Down'><span>1.0x</span></a>");var Cb=p.find(".speed-label"),Db=p.find(".speed-label span"),Xa=[1,.5,.25,1,1.5,2],Aa=1,Eb=Xa.length}if(ha){la.append("<a class='sound_button' title='Sound On/Off'><i class='fa fa-volume-off'></i></a>");
var Ca=p.find(".sound_button"),N=p.find(".sound_button i"),Fb=ha,Oa="sound-"+n,E}else"video-bg"!==A||ya||(la.append("<a class='sound_button' title='Sound On/Off'><i class='fa fa-volume-up'></i></a>"),Ca=p.find(".sound_button"),N=p.find(".sound_button i"),Ca.on("click",function(b){"html5"===ca?h.muted()?(N.removeClass("fa-volume-off").addClass("fa-volume-up"),h.muted(!1)):(N.removeClass("fa-volume-up").addClass("fa-volume-off"),h.muted(!0)):T.isMute?(N.removeClass("fa-volume-off").addClass("fa-volume-up"),
G.YTPUnmute(),T.isMute=!1):(N.removeClass("fa-volume-up").addClass("fa-volume-off"),G.YTPMute(),T.isMute=!0)}));if(!y.autoStart||y.controls){la.append("<a class='movie-button' title='Teaser Play/Pause'><i class='fa fa-play'></i></a>");var Ya=p.find(".movie-button"),Z=p.find(".movie-button i")}la.append("<a class='skip-button' title='Spring slideshowet over'><span>Spring over </span><i class='fa fa-angle-double-right'></i></a>");var db=p.find(".skip-button");p.find(".skip-button i");aa||ha||0<ka.length?b(window).load(function(){"xhr"===
y.preloadMethod?(H=new createjs.LoadQueue,H.installPlugin(createjs.Sound)):(H=new createjs.LoadQueue(!1),H.installPlugin(createjs.Sound),createjs.Sound.registerPlugins([createjs.HTMLAudioPlugin]));H.setMaxConnections(500);createjs.Sound.alternateExtensions=["ogg"];H.on("complete",$a);H.on("fileerror",Za);ha&&H.loadFile({id:Oa,src:Fb});H.loadManifest(ka)}):b(window).load(function(){if(!Ea&&("video-bg"===A&&"youtube"===ca||!I&&0<da.length))T.on("YTPReady",function(){0===ma&&(ia=O.find(".mbYTP_wrapper"),
sa(A))});else sa()});F.init=function(){F.start(d,"start",y.autoStart);if(Ya)Ya.on("click",function(b){t[n].paused()?(t[n].resume(),Z.removeClass("fa-play").addClass("fa-pause"),"video-bg"!==A||qa||(V&&h.play(),G&&G.YTPPlay()),fa&&h.play(),ja&&G.YTPPlay(),"paused"!==ba&&Da()):1<=t[n].progress()?(ja=fa=qa=!1,t[n].restart(),Z.removeClass("fa-repeat").addClass("fa-pause")):(t[n].pause(),"video-bg"!==A||qa||ta(),fa&&h.pause(),ja&&G.YTPPause(),Z.removeClass("fa-pause").addClass("fa-play"),"undefined"!==
typeof E&&(E.paused=!0,N.removeClass("fa-volume-up").addClass("fa-volume-off")))});if(y.controls)Cb.on("click",function(b){b=Xa[Aa];var c=isFloat(b)?b:b.toFixed(1);Db.html(c+"x");Aa=Aa<Eb-1?Aa+1:0;t[n].timeScale(b)});la.css({visibility:"visible"});if(y.showAnimationSummary)Wa.on("click",function(b){Wa.toggleClass("active")});return F};F.start=function(d,c,f){Ta=d.clone(!0);ma+=1;ea.hide();U.pause();t[n]=new TimelineMax({paused:!0,delay:.2,repeat:0,onStart:cb});"single-image"===A&&jb(t[n]);d=d.find(".sven-slide");
var h=d.length;d.each(function(a,c){var e=b(this).data(),d=e.anim;if(!e.sceneVideo&&e.sceneImage||I&&e.sceneImage)e.trans=e.trans?e.trans:"fade-in-bg";e.alignment||(e.alignment="center-center");e.pursueVideo||(e.pursueVideo="yes");I&&e.mobileAlignment&&(e.alignment=e.mobileAlignment);e.trans||(e.trans="none");e.freezeTime||(e.freezeTime="default");e.transDur||(e.transDur="default");d||(d="none");var f;f="left-top"===e.alignment||"left-bottom"===e.alignment||"left-center"===e.alignment?d+" halign-left":
"right-top"===e.alignment||"right-bottom"===e.alignment||"right-center"===e.alignment?d+" halign-right":d+" halign-center";if("none"!==d){b(this).find(".content-container").wrap("<div class='sven-scene "+f+"'><div class='centered "+e.alignment+"'></div></div>");var g=b(this).find(".content-container"),k=g.find("h1")}a==h-1&&(e.outDur="none",Ga=b(this).attr("id"));mb(b(this),a,e,t[n]);if("sequenital-fall-lt"===d||"sequential-fall-lt"===d)Ra(b(this),a,e,g,k,t[n],!0);else if("fall-hide-lt"===d)Ra(b(this),
a,e,g,k,t[n],!1);else if("appear-lt"===d){var l=b(this),q=g,u=t[n],v=J(l,e,q,k,!0,!1),k=v.content0.data().inEase?v.content0.data().inEase:"",g=v.content0.data().outEase?D(v.content0.data().outEase):"";u.set(v.wrapper0,{opacity:0});if(v.content1){var p=v.content1.data().inEase?v.content1.data().inEase:Bounce.easeOut,w=v.content1.data().outEase?D(v.content1.data().outEase):"";u.set(v.wrapper1,{overflow:"hidden"});u.set([v.content1,v.backdrop1],{y:"-104%"})}u.set(q,{visibility:"visible"});u.addLabel(v.marker);
u=L(!0);u.repeat.to(v.wrapper0,2.5,{delay:.8,opacity:1,ease:k});u["in"].add(u.repeat);v.content1&&u["in"].to([v.content1,v.backdrop1],.8,{y:"0%",ease:p});e.inDur&&u["in"].duration(parseFloat(e.inDur));"none"!=e.outDur&&(v.content1&&u.out.to([v.content1,v.backdrop1],.1,{y:"-100%",ease:w}),u.out.add(u.repeat.tweenFromTo(0,u.repeat.duration(),{ease:g}).timeScale(2).reverse()),e.outDur&&u.out.duration(parseFloat(e.outDur)));M(l,u,a,e,v.marker,q,!0)}else if("rotate-in-reveal-lt"===d)rb(b(this),a,e,g,k,
t[n]);else if("stripes-reveal-lt"===d)vb(b(this),a,e,g,k,t[n]);else if("random-reveal-lt"===d)ob(b(this),a,e,g,k,t[n]);else if("rainfall-reveal-lt"===d)pb(b(this),a,e,g,k,t[n]);else if("scale-reveal-lt"===d)qb(b(this),a,e,g,k,t[n]);else if("particles-reveal-lt"===d)sb(b(this),a,e,g,k,t[n]);else if("scale-rotate-lt"===d){var l=b(this),q=g,p=t[n],k=J(l,e,q,k,!1,!1),y,d=k.split0;f=k.content0.data().staggerTime?parseFloat(k.content0.data().staggerTime):.05;y=k.content0.data().inPattern?k.content0.data().inPattern:
"sequential";w=k.content0.data().inEase?k.content0.data().inEase:Back.easeOut;g=k.content0.data().outEase?D(k.content0.data().outEase):"";d.chars=K(y,d.chars);y=Math.ceil(parseInt(k.content0.css("line-height")));k.content1&&(u=k.content1.data().inEase?k.content1.data().inEase:Bounce.easeOut,v=k.content1.data().outEase?D(k.content1.data().outEase):"",p.set(k.wrapper1,{overflow:"hidden"}),p.set([k.content1,k.backdrop1],{y:"-104%"}));p.set(q,{visibility:"visible"});p.addLabel(k.marker);p=L(!0);p.repeat.staggerFrom(d.chars,
.8,{opacity:0,scale:0,y:y,rotationX:180,transformOrigin:"0% 50%",ease:w},f);p["in"].add(p.repeat);k.content1&&p["in"].to([k.content1,k.backdrop1],.8,{y:"0%",ease:u});e.inDur&&p["in"].duration(parseFloat(e.inDur));"none"!=e.outDur&&(k.content1&&p.out.to([k.content1,k.backdrop1],.1,{y:"-100%",ease:v}),p.out.add(p.repeat.tweenFromTo(0,p.repeat.duration(),{ease:g}).timeScale(2).reverse()),e.outDur&&p.out.duration(parseFloat(e.outDur)));M(l,p,a,e,k.marker,q,!0)}else if("random-alpha-reveal-lt"===d)tb(b(this),
a,e,g,k,t[n]);else if("blur-reveal-lt"===d)ub(b(this),a,e,g,k,t[n]);else if("flyin-reveal-lt"===d){var u=b(this),v=g,w=t[n],k=J(u,e,v,k,!1,!1),A;f=k.split0;g=f.chars.slice(0);p=f.chars.slice(0);k.content0.hasClass("place-left")?(d="-"+Math.ceil(k.wrapper0.offset().left+k.wrapper0.outerWidth())+"px",y="sequential",A="reverse"):(d=Math.ceil(wa(k.wrapper0,u)+k.wrapper0.outerWidth())+"px",y="reverse",A="sequential");w.set(f.chars,{x:d,opacity:0});y=k.content0.data().inPattern?k.content0.data().inPattern:
y;A=k.content0.data().outPattern?k.content0.data().outPattern:A;f=k.content0.data().inEase?D(k.content0.data().inEase):Back.easeOut;d=k.content0.data().outEase?D(k.content0.data().outEase):Back.easeIn.config(4);g=K(y,g);p=K(A,p);if(k.content1){var l=k.content1.data().inEase?k.content1.data().inEase:Back.easeOut,q=k.content1.data().outEase?D(k.content1.data().outEase):"",B;k.content1.hasClass("place-left")?(B=k.content1.offset().left,y="right center",A="-"+Math.ceil(B+k.content1.outerWidth())+"px"):
k.content1.hasClass("place-right")?(B=wa(k.content1,u),y="left center",A=Math.ceil(B+k.content1.outerWidth())+"px"):(B=wa(k.backdrop1,u),y="left center",A=Math.ceil(B+k.backdrop1.outerWidth())+"px");B=Ja(B,k.content1);w.set(k.backdrop1,{x:A,transformOrigin:y,scaleX:B});w.set(k.content1,{opacity:0})}w.set(v,{visibility:"visible"});w.addLabel(k.marker);w=L(!0);w["in"].staggerTo(g,1.3,{x:0,opacity:1,ease:f},.15);g=w["in"].duration();k.content1&&(w.repeat.to(k.backdrop1,.5*g,{scaleX:1,x:0,ease:l}),w.repeat.to(k.content1,
.5,{opacity:1}),w["in"].add(w.repeat,.18*g));e.inDur&&w["in"].duration(parseFloat(e.inDur));"none"!=e.outDur&&(w.out.staggerTo(p,1,{y:"100%",opacity:0,ease:d},.08),k.content1&&w.out.add(w.repeat.tweenFromTo(0,w.repeat.duration(),{ease:q}).timeScale(2).reverse(),.5),e.outDur&&w.out.duration(parseFloat(e.outDur)));M(u,w,a,e,k.marker,v,!0)}else"dominos-reveal-lt"===d?wb(b(this),a,e,g,k,t[n]):"glitch-one-lt"===d?xb(b(this),a,e,g,k,t[n]):"none"!==d&&console.log("The animation you mentioned in "+c.id+" does not exist. Check data-anim spelling for errors")});
var a=d=t[n].totalDuration();"default"!=y.fullDuration&&0<y.fullDuration&&(a=y.fullDuration,t[n].totalDuration(a));if(y.showAnimationSummary){var l="Teaser Duration: "+a.toFixed(1)+"s";Bb.html(l)}if("single-image"===A&&Ha){var l=new TimelineMax({delay:0}),p=Ha;d="auto"===La||isNaN(La)?((d-Qa)/d*a).toFixed(1):La;"in"===Va?l.fromTo(S,d,{scale:1},{scale:p,rotation:.02,transformOrigin:xa}):"out"===Va?l.fromTo(S,d,{scale:p},{scale:1,rotation:.02,transformOrigin:xa}):(l.fromTo(S,d/2,{scale:1},{scale:p,
rotation:.02,transformOrigin:xa}),l.to(S,d/2,{scale:1,rotation:.02,transformOrigin:xa}));ga.add(l,"imageZoomer")}t[n].set({},{onComplete:fb});f?F.play(c):F.seek(c);return F};F.play=function(b){"start"===b?t[n].play():t[n].play(b);Z&&Z.removeClass("fa-play").addClass("fa-pause");return F};F.seek=function(b){t[n].seek(b);Z.removeClass("fa-pause").addClass("fa-play");return F};F.restart=function(){t[n].restart();return F};F.pause=function(){t[n].pause();Z.removeClass("fa-pause").addClass("fa-play");
return F};b(window).on("debouncedresize",function(g){if(0<ma){if(!I||b(window).width()!=Ua){Ua=b(window).width();ea.show();U.play();g=t[n].paused()?!1:!0;var c=t[n].time();t[n].kill();d.remove();d=Ta;p.prepend(d);p.find(".sven-fullscreen").fullscreenBackground({defaultCss:!1});F.start(d,c,g)}}else console.log("TEASER NOT YET INITIALIZED")})};b.fn.svenPlugin=function(d){var P=this;return this.each(function(){if(void 0==b(this).data("svenPlugin")){var R=new b.svenPlugin(P,d);b(this).data("svenPlugin",
R)}})}})(jQuery);function randomInt(b,d){return Math.floor(Math.random()*(d-b+1)+b)}function randomFloat(b,d){return(Math.random()*(d-b)+b).toFixed(1)}function isFloat(b){return b===+b&&b!==(b|0)}function shuffleArray(b){for(var d=b.length-1;0<d;d--){var P=Math.floor(Math.random()*(d+1)),R=b[d];b[d]=b[P];b[P]=R}return b}function centerArray(b){for(var d=[],P=Math.ceil(b.length/2),R=P-1;0<=R;)d.push(b[R--]),P<b.length&&d.push(b[P++]);return d};
